blank_issues_enabled: false
contact_links:
  - name: 24/7 Mirrorbot Channel
    url: https://t.me/mirror_247_chennel
    about: Update Channel
  - name: 24/7 Mirrorbot Group
    url: https://t.me/mirror_247_chat
    about: Mirror/Support Group